version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    machine:
        enabled: true
    working_directory: ~/XTStackOverflow  
    steps:
       - run:
          name: Heroku container login
          command: heroku container:login
       - run:
          name: Heroku docker build
          command: heroku container:push web
       - run:
          name: Heroku docker push
          command: heroku container:release web
      
workflows:
    version: 2
    build_and_test:
      jobs:
        - build:
            filters:
              branches:
                only: dev_ruchik
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: dev_ruchik