version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    machine:
        enabled: true
    working_directory: ~/XTStackOverflow  
    #pINK
    steps:
       - checkout
       - run: 
          name: test current dir
          command: ls -la
       - run: 
          name: test docker
          command: docker ps -a
       - run:
          name: check image 
          command: docker image ls    
       - run:
          name: docker build image
          command: docker build -t xt .
       - run:
          name: Push to docker hub
          command: |
             docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            #  docker push srikarsharma/xt:latest
       - run: 
          name: heroku container deploy
          command: |
            #  heroku plugins:install heroku-container-registry
            #  heroku container:login
            #  heroku container:push web --app $HEROKU_APP_NAME
            # #  heroku container:release web
             docker login --username=SrikarMadipalli --password=$HEROKU_API_KEY registry.heroku.com
             docker image ls
             docker ps -a
             docker tag xt:latest registry.heroku.com/$HEROKU_APP_NAME/web
             docker push registry.heroku.com/$HEROKU_APP_NAME/web
      
workflows:
    version: 2
    build_and_test:
      jobs:
        - build:
            filters:
              branches:
                only: dev_ruchik
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: dev_ruchik