# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
service:
  - docker
dependencies:
  cache_directories:
    - ~/docker
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deployment:
    staging:
      branch: master
      commands:
        - docker login --email=$HEROKU_EMAIL --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
        - docker build --rm=false -t registry.heroku.com/APP_NAME/web .
        - docker push registry.heroku.com/APP_NAME/web:latest
